unbind r
bind r source-file ~/.tmux.conf

# Copy mode to vi
set-window-option -g mode-keys vi

set -g allow-passthrough on
set -g mouse on

# Vim motions baby
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# prefix not active
set -g status-style bg=default,fg=green

# prefix is active
set -g status-left "#{?client_prefix,#[bg=red],#[bg=default]} > #S < "
