
[window]
startup_mode = "Windowed"
padding = { x = 2, y = 0 }
opacity = 0.95 

[font]
size = 10
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
bold = { family = "FiraCode Nerd Font Mono", style = "Bold" }
italic = { family = "FiraCode Nerd Font Mono", style = "Italic" }
bold_italic = { family = "FiraCode Nerd Font Mono", style = "Bold Italic" }

[keyboard]
bindings = [
  { key = "T", mods = "Control|Shift", action = "SpawnNewInstance" },
]

# background = '#0a0c10'
# foreground = '#f0f3f6'
# Background thing
#[colors.primary]
#background = '#080808'

# Cursor color
[colors.cursor]
text = "#000000"
cursor = "#aaff3b"

[cursor]
style = { shape = "Block", blinking = "Always"}
blink_timeout = 0
blink_interval = 500
