animations = (
{
	triggers = ["open"];
	scale-y = {
		curve = "cubic-bezier(0,.73,.44,1.01)";
		start = 0;
		end = 1;
		duration = 0.2;
	};
	offset-y = {
		curve = "cubic-bezier(0,.73,.44,1.01)";
		duration = 0.2;
		start = "(window-height / 2)";
		end = 0;
	};
},
{
	triggers = ["close"];
	scale-y = {
		curve = "cubic-bezier(0,.73,.44,1.01)";
		duration = 0.5;
		start = 1;
		end = 0;
	};
	offset-y = {
		curve = "cubic-bezier(0,.73,.44,1.01)";
		duration = 0.5;
		start = 0;
		end = "(window-height / 2)";
	};
	opacity = {
		curve = "linear";
		duration = 0.3;
		start = "window-raw-opacity-before";
		end = 0;
	};
}
);

# --- Backend Settings ---
# Use glx (OpenGL) for better performance on Arch
backend = "glx";
vsync = true;

# --- Shadows ---
shadow = false;

# --- Fading (Instant) ---
#fading = true;
#fade-in-step = 0.04;  # 1 means 100% opacity change in one go
#fade-out-step = 0.04;
#fade-delta = 5;    # Minimum delay
fading = true;
fade-in-step = 0.05;
fade-out-step = 0.05;
no-fading-openclose = false;


# --- Corner Transparency Fix ---
experimental-backends = true;

# Corner radius (if you want picom to round EVERYTHING)
# corner-radius = 10;
# Some blur
# blur-method = "dual_kawase";
# blur-strength = 5;      # Adjust from 1 to 20 (5 is a good "frosted" middle ground)
# blur-background = true;

#{
#	triggers = ["geometry"];
#	offset-x = {
#		curve = "cubic-bezier(0,.73,.44,1.01)";
#		duration = 0.5;
#		start = "window-x-before - window-x";
#		end = 0;
#	};
#	offset-y = {
#		curve = "cubic-bezier(0,.73,.44,1.01)";
#		duration = 0.55;
#		start = "window-y-before - window-y";
#		end = 0;
#	};
#}
